import re

# Input SAM file generated by minimap2
input_sam = "Final_lncRNA_sequences_todas_cdhit_c09_cov09_R570_minimap2.sam"

# Output SAM file containing only perfect matches
output_sam = "Final_lncRNA_sequences_todas_cdhit_c09_cov09_R570_minimap2_filtered_100match.sam"

# Regular expression to accept only CIGAR strings
# composed of M (match/alignment) and N (splicing/introns)
# Examples accepted:
#   301M72N535M486N200M
#   553M5295N79M85N84M
valid_cigar = re.compile(r'^(\d+[MN])+$')

# Open input and output files
with open(input_sam) as infile, open(output_sam, "w") as outfile:

    # Read SAM file line by line
    for line in infile:

        # Keep SAM header lines unchanged
        if line.startswith("@"):
            outfile.write(line)
            continue

        # Split SAM fields by tab
        fields = line.strip().split('\t')

        # Extract CIGAR string (6th SAM column)
        cigar = fields[5]

        # Initialize NM value
        nm = None

        # Search optional SAM tags for NM:i
        # NM:i:0 means:
        #   no mismatches
        #   no insertions
        #   no deletions
        for field in fields[11:]:
            if field.startswith("NM:i:"):
                nm = int(field.split(":")[-1])
                break

        # Keep alignment only if:
        # 1. NM == 0 (perfect alignment)
        # 2. CIGAR contains only M and N operations
        #    (no I, D, S, H, etc.)
        if nm == 0 and valid_cigar.match(cigar):
            outfile.write(line)

print("Filtering completed.")
